# FROM nginx

# COPY . /usr/share/nginx/html
# COPY nginx.conf /etc/nginx/conf.d/default.conf

# WORKDIR /usr/share/nginx/html

# RUN ln -s public html \
#     && apt-get update \
#     && apt-get install -y vim \
#     && rm -rf /var/lib/apt/lists/*

# EXPOSE 80

# FROM php:8.1-apache

# RUN apt-get update \
#  && apt-get install -y git zlib1g-dev \
#  && docker-php-ext-install zip \
#  && a2enmod rewrite \
#  && sed -i 's!/var/www/html!/var/www/public!g' /etc/apache2/sites-available/000-default.conf \
#  && mv /var/www/html /var/www/public \
#  && curl -sS https://getcomposer.org/installer \
#   | php -- --install-dir=/usr/local/bin --filename=composer \
#  && echo "AllowEncodedSlashes On" >> /etc/apache2/apache2.conf

# WORKDIR /var/www

# FROM php:8.2.4RC1-fpm

# WORKDIR /var/www/html/

# RUN php -r "readfile('http://getcomposer.org/installer');" | php -- --install-dir=/usr/bin/ --filename=composer

# COPY . .

# RUN composer install